name: Sync RSS from OneDrive
on:
  schedule:
    - cron: "*/10 * * * *" # Runs every 10 minutes
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download RSS from OneDrive
        run: |
          curl -L "https://086gc-my.sharepoint.com/:u:/g/personal/kevin_el-saikali_dfo-mpo_gc_ca/EdrDgLtiBzZNrRKrFNqSp1ABtD72_RVrStgWvBGBOJvDUQ?e=DL7sjZ" -o new_newsfeed.xml


      - name: Check if file changed
        run: |
          if cmp -s new_newsfeed.xml newsfeed.xml; then
            echo "No changes detected. Skipping commit."
            exit 0
          else
            mv new_newsfeed.xml newsfeed.xml
          fi


      - name: Commit and Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add newsfeed.xml
          git diff --cached --quiet || (git commit -m "Update RSS from OneDrive" && git push)

