name: Sync RSS from OneDrive
on:
  schedule:
    - cron: "*/10 * * * *" # Runs every 10 minutes
  workflow_dispatch: # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download RSS from OneDrive
        run: |
          curl -L "YOUR_ONEDRIVE_DIRECT_DOWNLOAD_LINK" -o rss.xml

      - name: Commit and Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add rss.xml
          git commit -m "Update RSS from OneDrive"
          git push
