name: Sync RSS from OneDrive
on:
  schedule:
    - cron: "*/10 * * * *" # Runs every 10 minutes
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download RSS from OneDrive
        run: |
          curl -L "https://086gc-my.sharepoint.com/:u:/g/personal/kevin_el-saikali_dfo-mpo_gc_ca/ESmFiG21Wa5JtDuXOjy9lqMBZu_Ywo94tCuovYl5ZaLFfw?e=hbcZHe" -o new_rss.xml

      - name: Check if file changed
        run: |
          if cmp -s new_rss.xml rss.xml; then
            echo "No changes detected. Skipping commit."
            exit 0
          else
            mv new_rss.xml rss.xml
          fi

      - name: Commit and Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add rss.xml
          git commit -m "Update RSS from OneDrive" || echo "No changes to commit"
          git push


