name: Sync RSS from OneDrive
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download RSS from OneDrive
        run: |
          curl -L "https://086gc-my.sharepoint.com/:u:/r/personal/kevin_el-saikali_dfo-mpo_gc_ca/Documents/Attachments/rss.xml?csf=1&web=1&e=ry2aKs" -o new_rss.xml

      - name: Validate and Compare
        run: |
          if [ ! -s new_rss.xml ]; then
            echo "Downloaded file is empty. Skipping update."
            exit 0
          fi

          if [ -f rss.xml ] && cmp -s new_rss.xml rss.xml; then
            echo "No changes detected. Skipping commit."
            exit 0
          fi

          mv new_rss.xml rss.xml

      - name: Commit and Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add rss.xml
          git commit -m "Update RSS from OneDrive" || echo "No changes to commit"
          git push
